/** Generated by `bun run row-schema`; do not edit. */
export const ROW_SCHEMA_FINGERPRINTS = {
  editor: 'wheel-rows-sha256:3998a289fe7bd8740b5d0bf44531dfcc5066ee8ae52e61660daeb6e4384c3dca',
  graph: 'wheel-rows-sha256:cbce69e33506044b78090017dd52bb1387124d8862d9194e68ee78b15110eacf',
  kanban: 'wheel-rows-sha256:a76edaa1869e5deedf473fe89d76cac4e5c5c3c2b827bc06cf6e5cd61d3a26ba',
  sequencer: 'wheel-rows-sha256:312d844d9921abcb991bec88d22b1bef4dd8b0ea30b72a0cbde90fd39992ab9a',
  sheet: 'wheel-rows-sha256:72c0c10f9678fc90801e16ca6a9aef1f111a9a22f4e68798360662f3303d323c',
  todos: 'wheel-rows-sha256:e38c8d7827479e29bb0cf891effbc8b820b29c4966ee899a06d6eaae83f1cca2',
} as const;
