/** Generated by `bun run row-schema`; do not edit. */
export const ROW_SCHEMA_FINGERPRINTS = {
  editor: 'wheel-rows-sha256:44ea1f970d861e89b9a9840ebf080ec26f2f670b77f60c10c49b6c58fd3a3c80',
  graph: 'wheel-rows-sha256:b78c11129e61770c87f79a57da77d93f7a3f82993d6020b4e8636a9ca390e9c2',
  kanban: 'wheel-rows-sha256:a542caeff6b4907937ced2add545715f9b671ca201b55e58ac99648de14312fd',
  sequencer: 'wheel-rows-sha256:ef9dab4306791a8b89c899dd4415c52f53485529dd1751fb66a7c7266f5fca14',
  sheet: 'wheel-rows-sha256:e797d6a2177d6a229df6e2fcae7b03f107396bcb5d1330806fae2bad2256a992',
  todos: 'wheel-rows-sha256:a9d75f89e7e213e531c69b8cd60528ec0997cc0a3a198b9a9b5ea6a117f84171',
} as const;
