/**
 * Wheel-owned client state materialization.
 *
 * The materializer keeps confirmed query state separate from pending commands.
 * Each rebuild replays complete commands on private collection forks, derives query
 * results, and publishes one final view.
 */
import { canonicalParams } from '../../core/params';
import {
  OrphanedError,
  validateCollectionKey,
  type CacheReader,
  type InverseSpec,
  type MutationDecl,
  type QueryDecl,
  type CollectionDecl
} from '../declarations';
import { jsonParseIsIdentity, validateJsonValue, validateRow } from '../schema';
import type { SyncQueryStatus } from '../protocol';
import { cloneCollections, freezeRow, OverlayCache, collectionMap, type RecordedWrite, type Row, type Collections } from './cache';

type AnyMutationDecl = MutationDecl<any>;
type AnyQueryDecl = QueryDecl<any, any>;

/** Lifecycle state stored beside one materialized query scope. */
export type MaterializerQueryStatus =
  | { readonly kind: 'loading' }
  | SyncQueryStatus;

/** One existing mutation declaration and the data needed to replay it. */
export interface MaterializerCall<Args extends Record<string, unknown> = Record<string, unknown>> {
  readonly mutation: MutationDecl<Args>;
  readonly args: Args;
  /** IDs generated by this member's original optimistic run, in call order. */
  readonly ids: readonly string[];
}

/** One pending command. Several calls form one atomic mutation group. */
export interface MaterializerCommand {
  readonly mutationId: string;
  readonly calls: readonly MaterializerCall<any>[];
  /** `mutateGroup` sets this; plain `mutate` permits a non-invertible single call. */
  readonly requireUndo: boolean;
  /** Present only for a command's first optimistic run. Replay uses the stored ID stream. */
  readonly newId?: (prefix: string) => string;
}

/** Complete server result state for one query scope inside a confirmed batch. */
export interface MaterializerQueryUpdate {
  readonly query: AnyQueryDecl;
  readonly params: Record<string, unknown>;
  readonly puts?: readonly Row[];
  readonly deletes?: readonly string[];
  readonly order: readonly string[];
  readonly status: MaterializerQueryStatus;
}

/** One atomic confirmed input to the materializer. */
export interface MaterializerServerBatch {
  readonly queries: readonly MaterializerQueryUpdate[];
  /** Commands whose confirmed rows are present in this same batch. */
  readonly settledCommandIds?: readonly string[];
}

/** Terminal or pending result returned by the materializer command boundary. */
export interface MaterializerCommandResult {
  readonly state: 'pending' | 'confirmed' | 'rejected' | 'failed' | 'orphaned';
  readonly message?: string;
}

/** One public notification emitted after a complete view has replaced the prior view. */
export interface MaterializerPublication {
  readonly revision: number;
  readonly changedCollections: ReadonlySet<string>;
}

interface PreparedCall {
  readonly mutation: AnyMutationDecl;
  readonly args: Record<string, unknown>;
  readonly ids: readonly string[];
}

interface PendingCommand {
  readonly mutationId: string;
  readonly calls: readonly PreparedCall[];
  readonly inverses: readonly InverseSpec[];
  readonly requireUndo: boolean;
  readonly writes: readonly RecordedWrite[];
  /** Durable optimistic output shown until the first confirmed input can trigger semantic replay. */
  readonly preview?: readonly RecordedWrite[];
}

interface QueryScope {
  readonly key: string;
  readonly query: AnyQueryDecl;
  readonly params: Record<string, unknown>;
  readonly order: readonly string[];
  readonly status: MaterializerQueryStatus;
}

interface PublishedView {
  readonly revision: number;
  readonly collections: Collections;
  readonly queryRows: ReadonlyMap<string, readonly Row[]>;
  readonly queryStatuses: ReadonlyMap<string, MaterializerQueryStatus>;
  readonly queryCollections: ReadonlyMap<string, string>;
}

interface BuildResult {
  readonly view: PublishedView;
  readonly pending: readonly PendingCommand[];
  readonly outcomes: readonly [string, MaterializerCommandResult][];
}

/** Canonical identity for one declared query and parameter object. */
export function materializerQueryKey(query: AnyQueryDecl, params: Record<string, unknown>): string {
  return `${query.name}|${canonicalParams(params)}`;
}

function collectionReader(collections: Collections): CacheReader {
  return {
    get: (collection, id) => collectionMap(collections, collection.name).get(id) as never,
    list: (collection) => [...collectionMap(collections, collection.name).values()] as never
  };
}

function rowsEqual(left: readonly Row[] | undefined, right: readonly Row[] | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.length !== right.length) return false;
  return left.every((row, index) => row === right[index]);
}

function statusEqual(left: MaterializerQueryStatus | undefined, right: MaterializerQueryStatus | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.kind !== right.kind) return false;
  if (left.kind === 'stale' && right.kind === 'stale') return left.error === right.error;
  if (left.kind === 'error' && right.kind === 'error') return left.error === right.error;
  return true;
}

function mapEqual(left: ReadonlyMap<string, Row> | undefined, right: ReadonlyMap<string, Row> | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.size !== right.size) return false;
  for (const [key, value] of left) {
    if (right.get(key) !== value) return false;
  }
  return true;
}

/**
 * Every mutating method stages confirmed and optimistic work first. The class
 * swaps its readable view and calls listeners only after the stage succeeds.
 */
export class WheelMaterializer {
  readonly #listeners = new Set<(publication: MaterializerPublication) => void>();
  readonly #outcomes = new Map<string, MaterializerCommandResult>();
  #confirmed: Collections = new Map();
  #scopes = new Map<string, QueryScope>();
  #pending: readonly PendingCommand[] = [];
  #view: PublishedView = {
    revision: 0,
    collections: new Map(),
    queryRows: new Map(),
    queryStatuses: new Map(),
    queryCollections: new Map()
  };

  constructor(
    private readonly options: {
      readonly actor: string;
      readonly now: () => number;
      /** Production keeps replay failures until the server verdict identifies their cause. */
      readonly retainReplayFailures?: boolean;
    }
  ) {}

  /** Current publication revision. It changes once per accepted state input. */
  revision(): number {
    return this.#view.revision;
  }

  /** Subscribe to final publications. Intermediate rebuild state is never passed to listeners. */
  onPublish(listener: (publication: MaterializerPublication) => void): () => void {
    this.#listeners.add(listener);
    return () => this.#listeners.delete(listener);
  }

  /** Read one row from the current effective view. */
  get<RowT extends Row>(collection: CollectionDecl<RowT>, id: string): RowT | undefined {
    return collectionMap(this.#view.collections, collection.name).get(id) as RowT | undefined;
  }

  /** Read every pooled row of one collection from the current effective view. */
  rows<RowT extends Row>(collection: CollectionDecl<RowT>): readonly RowT[] {
    return [...collectionMap(this.#view.collections, collection.name).values()] as RowT[];
  }

  /** Every effective collection for diagnostics. */
  collectionsDebug(): Array<{ collection: string; rows: readonly Row[] }> {
    return [...this.#view.collections.entries()]
      .map(([collection, rows]) => ({ collection, rows: [...rows.values()] as readonly Row[] }))
      .sort((left, right) => left.collection.localeCompare(right.collection));
  }

  /** Read the current effective rows for one declared query scope. */
  queryRows<Params extends Record<string, unknown>, RowT extends Row>(
    query: QueryDecl<Params, RowT>,
    params: Params
  ): readonly RowT[] {
    return (this.#view.queryRows.get(materializerQueryKey(query, params)) ?? []) as readonly RowT[];
  }

  /** Read lifecycle state for a query, including an empty result. */
  queryStatus<Params extends Record<string, unknown>, RowT extends Row>(
    query: QueryDecl<Params, RowT>,
    params: Params
  ): MaterializerQueryStatus | undefined {
    return this.#view.queryStatuses.get(materializerQueryKey(query, params));
  }

  /** Confirmed server order for one query scope. */
  queryOrder(query: AnyQueryDecl, params: Record<string, unknown>): readonly string[] {
    return this.#scopes.get(materializerQueryKey(query, params))?.order ?? [];
  }

  /** Confirmed rows for persistence. Optimistic writes are deliberately excluded. */
  confirmedQueryRows(query: AnyQueryDecl, params: Record<string, unknown>): readonly Row[] {
    const scope = this.#scopes.get(materializerQueryKey(query, params));
    if (!scope) return [];
    const rows = collectionMap(this.#confirmed, query.into.name);
    return scope.order.map((id) => rows.get(id)).filter((row): row is Row => row !== undefined);
  }

  /** Read one confirmed row for rollback provenance. */
  confirmedGet(collectionName: string, id: string): Row | undefined {
    return collectionMap(this.#confirmed, collectionName).get(id);
  }

  /** Current state for a command removed during replay or explicitly settled. */
  commandState(mutationId: string): MaterializerCommandResult | undefined {
    if (this.#pending.some((command) => command.mutationId === mutationId)) return { state: 'pending' };
    return this.#outcomes.get(mutationId);
  }

  /** Reverse-ordered inverses captured for one pending command. */
  commandInverses(mutationId: string): readonly InverseSpec[] {
    return this.#pending.find((command) => command.mutationId === mutationId)?.inverses ?? [];
  }

  /** Validated calls and deterministic IDs stored for one pending command. */
  commandCalls(mutationId: string): readonly MaterializerCall<any>[] {
    return this.#pending.find((command) => command.mutationId === mutationId)?.calls ?? [];
  }

  /** Current complete write set for one pending command. */
  commandWrites(mutationId: string): readonly RecordedWrite[] {
    return this.#pending.find((command) => command.mutationId === mutationId)?.writes ?? [];
  }

  /** Whether a restored command still waits for enough confirmed state to replay. */
  commandUsesPreview(mutationId: string): boolean {
    return this.#pending.find((command) => command.mutationId === mutationId)?.preview !== undefined;
  }

  /** Replay failure retained until SyncClient can compare it with the server verdict. */
  commandReplayFailure(mutationId: string): MaterializerCommandResult | undefined {
    const result = this.#outcomes.get(mutationId);
    return result?.state === 'failed' || result?.state === 'orphaned' ? result : undefined;
  }

  /** Pending command IDs in semantic replay order. */
  pendingCommandIds(): readonly string[] {
    return this.#pending.map((command) => command.mutationId);
  }

  /**
   * Apply one atomic server batch, then replay surviving pending commands.
   * Query updates contain complete final order but may contain delta-only puts.
   */
  applyServerBatch(batch: MaterializerServerBatch): void {
    const nextConfirmed = cloneCollections(this.#confirmed);
    const nextScopes = new Map(this.#scopes);
    const pruneCandidates = new Map<string, Set<string>>();
    const seenScopes = new Set<string>();

    for (const update of batch.queries) {
      const parsedParams = update.query.params.safeParse(update.params);
      if (!parsedParams.success || !jsonParseIsIdentity(update.params, parsedParams.data)) {
        throw new Error(`Params for materializer query "${update.query.name}" are invalid.`);
      }
      validateJsonValue(`Params for materializer query "${update.query.name}"`, parsedParams.data);
      const params = parsedParams.data as Record<string, unknown>;
      const key = materializerQueryKey(update.query, params);
      if (seenScopes.has(key)) throw new Error(`Materializer batch contains query scope "${key}" twice.`);
      seenScopes.add(key);

      const order = [...update.order];
      const orderSet = new Set<string>();
      for (const id of order) {
        if (typeof id !== 'string' || id.trim() === '' || orderSet.has(id)) {
          throw new Error(`Materializer query "${update.query.name}" has an invalid or duplicate order key.`);
        }
        orderSet.add(id);
      }
      const deletes = new Set(update.deletes ?? []);
      for (const id of deletes) {
        if (orderSet.has(id)) {
          throw new Error(`Materializer query "${update.query.name}" both deletes and retains row "${id}".`);
        }
      }

      const collection = update.query.into;
      const collectionRows = collectionMap(nextConfirmed, collection.name);
      const putKeys = new Set<string>();
      for (const [index, raw] of (update.puts ?? []).entries()) {
        const row = freezeRow({
          ...validateRow(`materializer query ${update.query.name}`, collection.schema, raw)
        });
        const id = validateCollectionKey(collection, row, `Materializer query "${update.query.name}" put ${index}`);
        if (putKeys.has(id)) {
          throw new Error(`Materializer query "${update.query.name}" has duplicate put key "${id}".`);
        }
        putKeys.add(id);
        collectionRows.set(id, row);
      }

      const candidates = pruneCandidates.get(collection.name) ?? new Set<string>();
      for (const id of deletes) candidates.add(id);
      const previous = nextScopes.get(key);
      for (const id of previous?.order ?? []) {
        if (!orderSet.has(id)) candidates.add(id);
      }
      pruneCandidates.set(collection.name, candidates);
      nextScopes.set(key, {
        key,
        query: update.query,
        params,
        order: Object.freeze(order),
        status: update.status
      });
    }

    for (const scope of nextScopes.values()) {
      const rows = collectionMap(nextConfirmed, scope.query.into.name);
      for (const id of scope.order) {
        if (!rows.has(id)) {
          throw new Error(`Materializer query "${scope.query.name}" order references missing row "${id}".`);
        }
      }
    }
    this.#pruneUnclaimed(nextConfirmed, nextScopes, pruneCandidates);

    const settled = new Set(batch.settledCommandIds ?? []);
    const nextPending = this.#pending.filter((command) => !settled.has(command.mutationId));
    for (const mutationId of settled) {
      if (!this.#pending.some((command) => command.mutationId === mutationId)) {
        throw new Error(`Cannot settle unknown materializer command "${mutationId}".`);
      }
    }
    const built = this.#build(nextConfirmed, nextScopes, nextPending);
    this.#confirmed = nextConfirmed;
    this.#scopes = nextScopes;
    this.#pending = built.pending;
    for (const mutationId of settled) this.#outcomes.set(mutationId, { state: 'confirmed' });
    this.#recordBuildOutcomes(built);
    this.#publish(built.view);
  }

  /**
   * Validate and enqueue one single or grouped command. Group inverse failure
   * returns `failed` before the readable view changes.
   */
  enqueue(command: MaterializerCommand): MaterializerCommandResult {
    if (command.calls.length === 0) return { state: 'confirmed' };
    if (command.calls.length > 128) {
      const result = { state: 'failed', message: 'A mutation group may contain at most 128 members.' } as const;
      this.#outcomes.set(command.mutationId, result);
      return result;
    }
    if (this.#pending.some((pending) => pending.mutationId === command.mutationId) || this.#outcomes.has(command.mutationId)) {
      const result = { state: 'failed', message: `Duplicate materializer command "${command.mutationId}".` } as const;
      this.#outcomes.set(command.mutationId, result);
      return result;
    }

    const prepared = this.#prepareCalls(command.calls);
    if (!Array.isArray(prepared)) {
      this.#outcomes.set(command.mutationId, prepared);
      return prepared;
    }

    const preflight = cloneCollections(this.#view.collections);
    const inverses: InverseSpec[] = [];
    try {
      for (const [index, call] of prepared.entries()) {
        const inverse = call.mutation.invert?.(collectionReader(preflight), call.args) ?? null;
        if (command.requireUndo && inverse === null) {
          const result = {
            state: 'failed',
            message: `Mutation "${call.mutation.name}" is not invertible in this state.`
          } as const;
          this.#outcomes.set(command.mutationId, result);
          return result;
        }
        if (inverse) inverses.unshift(inverse);
        const applied = this.#applyCall(preflight, call, command.newId);
        prepared[index] = { ...call, ids: applied.ids };
      }
    } catch (error) {
      const result = error instanceof OrphanedError
        ? ({ state: 'orphaned', message: error.message } as const)
        : ({ state: 'failed', message: String((error as Error)?.message ?? error) } as const);
      this.#outcomes.set(command.mutationId, result);
      return result;
    }

    const pending: PendingCommand = {
      mutationId: command.mutationId,
      calls: Object.freeze(prepared),
      inverses: Object.freeze(inverses),
      requireUndo: command.requireUndo,
      writes: Object.freeze([])
    };
    const built = this.#build(this.#confirmed, this.#scopes, [...this.#pending, pending]);
    const ownFailure = built.outcomes.find(([mutationId]) => mutationId === command.mutationId)?.[1];
    if (ownFailure) {
      const withoutFailed = this.#build(
        this.#confirmed,
        this.#scopes,
        built.pending.filter((candidate) => candidate.mutationId !== command.mutationId)
      );
      this.#pending = withoutFailed.pending;
      this.#recordBuildOutcomes(withoutFailed);
      this.#outcomes.set(command.mutationId, ownFailure);
      this.#publish(withoutFailed.view);
      return ownFailure;
    }
    this.#pending = built.pending;
    this.#recordBuildOutcomes(built);
    this.#publish(built.view);
    return this.commandState(command.mutationId) ?? { state: 'failed', message: 'Command disappeared during replay.' };
  }

  /** Restore a durable command preview before confirmed rows finish hydrating. */
  restoreCommand(command: MaterializerCommand, preview: readonly RecordedWrite[]): MaterializerCommandResult {
    if (command.calls.length === 0) return { state: 'confirmed' };
    if (command.calls.length > 128) {
      return { state: 'failed', message: 'A mutation group may contain at most 128 members.' };
    }
    if (this.#pending.some((pending) => pending.mutationId === command.mutationId) || this.#outcomes.has(command.mutationId)) {
      return { state: 'failed', message: `Duplicate materializer command "${command.mutationId}".` };
    }
    const prepared = this.#prepareCalls(command.calls);
    if (!Array.isArray(prepared)) return prepared;
    const restored: PendingCommand = {
      mutationId: command.mutationId,
      calls: Object.freeze(prepared),
      inverses: Object.freeze([]),
      requireUndo: command.requireUndo,
      preview: Object.freeze([...preview]),
      writes: Object.freeze([...preview])
    };
    const built = this.#build(this.#confirmed, this.#scopes, [...this.#pending, restored], false);
    this.#pending = built.pending;
    this.#recordBuildOutcomes(built);
    this.#publish(built.view);
    return this.commandState(command.mutationId) ?? { state: 'failed', message: 'Command disappeared during restore.' };
  }

  /** Remove a rejected, failed, or orphaned command and publish the surviving replay. */
  removeCommand(mutationId: string, state: 'rejected' | 'failed' | 'orphaned'): boolean {
    if (!this.#pending.some((command) => command.mutationId === mutationId)) return false;
    const built = this.#build(
      this.#confirmed,
      this.#scopes,
      this.#pending.filter((command) => command.mutationId !== mutationId)
    );
    this.#pending = built.pending;
    this.#outcomes.set(mutationId, { state });
    this.#recordBuildOutcomes(built);
    this.#publish(built.view);
    return true;
  }

  /** Release one query scope and prune confirmed rows with no remaining server claim. */
  releaseQuery(query: AnyQueryDecl, params: Record<string, unknown>): boolean {
    const key = materializerQueryKey(query, params);
    const released = this.#scopes.get(key);
    if (!released) return false;
    const nextConfirmed = cloneCollections(this.#confirmed);
    const nextScopes = new Map(this.#scopes);
    nextScopes.delete(key);
    this.#pruneUnclaimed(
      nextConfirmed,
      nextScopes,
      new Map([[released.query.into.name, new Set(released.order)]])
    );
    const built = this.#build(nextConfirmed, nextScopes, this.#pending);
    this.#confirmed = nextConfirmed;
    this.#scopes = nextScopes;
    this.#pending = built.pending;
    this.#recordBuildOutcomes(built);
    this.#publish(built.view);
    return true;
  }

  #prepareCalls(calls: readonly MaterializerCall<any>[]): PreparedCall[] | MaterializerCommandResult {
    const prepared: PreparedCall[] = [];
    for (const call of calls) {
      const parsed = call.mutation.args.safeParse(call.args);
      if (!parsed.success || !jsonParseIsIdentity(call.args, parsed.data)) {
        return { state: 'failed', message: `Args for mutation "${call.mutation.name}" are invalid.` };
      }
      try {
        validateJsonValue(`Args for mutation "${call.mutation.name}"`, parsed.data);
      } catch (error) {
        return { state: 'failed', message: String((error as Error)?.message ?? error) };
      }
      prepared.push({
        mutation: call.mutation as AnyMutationDecl,
        args: parsed.data,
        ids: Object.freeze([...call.ids])
      });
    }
    return prepared;
  }

  #recordBuildOutcomes(built: BuildResult): void {
    for (const command of built.pending) this.#outcomes.delete(command.mutationId);
    for (const [mutationId, result] of built.outcomes) this.#outcomes.set(mutationId, result);
  }

  #applyCall(
    collections: Collections,
    call: PreparedCall,
    generateId?: (prefix: string) => string
  ): { readonly writes: readonly RecordedWrite[]; readonly ids: readonly string[] } {
    const overlay = new OverlayCache(collections);
    let nextId = 0;
    const generatedIds: string[] = [];
    call.mutation.optimistic?.(overlay, call.args, {
      actor: this.options.actor,
      now: this.options.now,
      newId: (prefix: string) => {
        if (generateId) {
          const id = generateId(prefix);
          generatedIds.push(id);
          return id;
        }
        const id = call.ids[nextId];
        nextId += 1;
        if (id === undefined) {
          throw new Error(`Mutation "${call.mutation.name}" exhausted its deterministic ID stream.`);
        }
        if (!id.startsWith(`${prefix}_`)) {
          throw new Error(`Mutation "${call.mutation.name}" expected a "${prefix}_" deterministic ID.`);
        }
        return id;
      }
    });
    if (!generateId && nextId !== call.ids.length) {
      throw new Error(`Mutation "${call.mutation.name}" left deterministic IDs unused.`);
    }
    return {
      writes: overlay.writes,
      ids: generateId ? Object.freeze(generatedIds) : call.ids
    };
  }

  #build(
    confirmed: Collections,
    scopes: ReadonlyMap<string, QueryScope>,
    pending: readonly PendingCommand[],
    activatePreviews = true
  ): BuildResult {
    let working = cloneCollections(confirmed);
    const surviving: PendingCommand[] = [];
    const outcomes: Array<[string, MaterializerCommandResult]> = [];
    const touched = new Map<string, Set<string>>();

    for (const command of pending) {
      const commandFork = cloneCollections(working);
      const writes: RecordedWrite[] = [];
      if (command.preview && !activatePreviews) {
        for (const write of command.preview) {
          const rows = collectionMap(commandFork, write.collection);
          if (write.value === undefined) rows.delete(write.rowId);
          else rows.set(write.rowId, freezeRow({ ...write.value }));
          writes.push(write);
        }
        working = commandFork;
        for (const write of writes) {
          const ids = touched.get(write.collection) ?? new Set<string>();
          ids.add(write.rowId);
          touched.set(write.collection, ids);
        }
        surviving.push({ ...command, writes: Object.freeze(writes) });
        continue;
      }
      try {
        for (const call of command.calls) writes.push(...this.#applyCall(commandFork, call).writes);
      } catch (error) {
        const outcome: MaterializerCommandResult =
          error instanceof OrphanedError
            ? { state: 'orphaned', message: error.message }
            : { state: 'failed', message: String((error as Error)?.message ?? error) };
        outcomes.push([
          command.mutationId,
          outcome
        ]);
        if (command.preview) {
          const previewFork = cloneCollections(working);
          for (const write of command.preview) {
            const rows = collectionMap(previewFork, write.collection);
            if (write.value === undefined) rows.delete(write.rowId);
            else rows.set(write.rowId, freezeRow({ ...write.value }));
            const ids = touched.get(write.collection) ?? new Set<string>();
            ids.add(write.rowId);
            touched.set(write.collection, ids);
          }
          working = previewFork;
          surviving.push(command);
          continue;
        }
        if (this.options.retainReplayFailures) {
          surviving.push(command);
        }
        continue;
      }
      working = commandFork;
      for (const write of writes) {
        const ids = touched.get(write.collection) ?? new Set<string>();
        ids.add(write.rowId);
        touched.set(write.collection, ids);
      }
      surviving.push({ ...command, preview: undefined, writes: Object.freeze(writes) });
    }

    const queryRows = new Map<string, readonly Row[]>();
    const queryStatuses = new Map<string, MaterializerQueryStatus>();
    const queryCollections = new Map<string, string>();
    for (const scope of scopes.values()) {
      const rows = collectionMap(working, scope.query.into.name);
      const ids = scope.order.filter((id) => rows.has(id));
      let hasProjectedWrites = false;
      if (scope.query.projection) {
        const membership = new Set(ids);
        for (const id of touched.get(scope.query.into.name) ?? []) {
          const row = rows.get(id);
          const wasMember = membership.has(id);
          const isMember = row !== undefined && scope.query.projection.filter(row, scope.params);
          if (wasMember || isMember) hasProjectedWrites = true;
          if (isMember) membership.add(id);
          else membership.delete(id);
        }
        ids.splice(0, ids.length, ...membership);
      }
      const result = ids.map((id) => rows.get(id)).filter((row): row is Row => row !== undefined);
      // Confirmed order belongs to the server. Re-sort only when optimistic
      // writes added, removed, or changed a row in this query scope.
      if (hasProjectedWrites && scope.query.projection?.sort) result.sort(scope.query.projection.sort);
      queryRows.set(scope.key, Object.freeze(result));
      queryStatuses.set(scope.key, scope.status);
      queryCollections.set(scope.key, scope.query.into.name);
    }

    return {
      view: {
        revision: this.#view.revision + 1,
        collections: working,
        queryRows,
        queryStatuses,
        queryCollections
      },
      pending: Object.freeze(surviving),
      outcomes
    };
  }

  #pruneUnclaimed(
    collections: Collections,
    scopes: ReadonlyMap<string, QueryScope>,
    candidates: ReadonlyMap<string, ReadonlySet<string>>
  ): void {
    for (const [collectionName, ids] of candidates) {
      const claimed = new Set<string>();
      for (const scope of scopes.values()) {
        if (scope.query.into.name === collectionName) {
          for (const id of scope.order) claimed.add(id);
        }
      }
      const rows = collectionMap(collections, collectionName);
      for (const id of ids) {
        if (!claimed.has(id)) rows.delete(id);
      }
    }
  }

  #changedCollections(next: PublishedView): Set<string> {
    const changed = new Set<string>();
    const collectionNames = new Set([...this.#view.collections.keys(), ...next.collections.keys()]);
    for (const collectionName of collectionNames) {
      if (!mapEqual(this.#view.collections.get(collectionName), next.collections.get(collectionName))) changed.add(collectionName);
    }
    const queryKeys = new Set([...this.#view.queryRows.keys(), ...next.queryRows.keys()]);
    for (const key of queryKeys) {
      if (
        !rowsEqual(this.#view.queryRows.get(key), next.queryRows.get(key)) ||
        !statusEqual(this.#view.queryStatuses.get(key), next.queryStatuses.get(key))
      ) {
        const collectionName = next.queryCollections.get(key) ?? this.#view.queryCollections.get(key);
        if (collectionName) changed.add(collectionName);
      }
    }
    return changed;
  }

  #publish(next: PublishedView): void {
    const changedCollections = this.#changedCollections(next);
    this.#view = next;
    const publication: MaterializerPublication = {
      revision: next.revision,
      changedCollections
    };
    for (const listener of this.#listeners) listener(publication);
  }
}
