/**
 * Internal Phase 0B proof for Wheel-owned client state materialization.
 *
 * The materializer keeps confirmed query state separate from pending commands.
 * Each rebuild replays complete commands on private table forks, derives query
 * results, and publishes one final view. This module is not exported from the
 * Wheel package and does not serve production reads during the proof phase.
 */
import { canonicalParams } from '../../core/params';
import {
  OrphanedError,
  validateTableKey,
  type CacheReader,
  type InverseSpec,
  type MutationDecl,
  type QueryDecl,
  type TableDecl
} from '../declarations';
import { jsonParseIsIdentity, validateJsonValue, validateRow } from '../schema';
import { cloneTables, freezeRow, OverlayCache, tableMap, type RecordedWrite, type Row, type Tables } from './cache';

type AnyMutationDecl = MutationDecl<any>;
type AnyQueryDecl = QueryDecl<any, any>;

/** Lifecycle state stored beside one materialized query scope. */
export type MaterializerQueryStatus =
  | { readonly kind: 'loading' }
  | { readonly kind: 'live' }
  | { readonly kind: 'stale'; readonly error?: unknown }
  | { readonly kind: 'error'; readonly error: unknown };

/** One existing mutation declaration and the data needed to replay it. */
export interface MaterializerCall<Args extends Record<string, unknown> = Record<string, unknown>> {
  readonly mutation: MutationDecl<Args>;
  readonly args: Args;
  /** IDs generated by this member's original optimistic run, in call order. */
  readonly ids: readonly string[];
}

/** One pending command. Several calls form one atomic mutation group. */
export interface MaterializerCommand {
  readonly mutationId: string;
  readonly calls: readonly MaterializerCall<any>[];
  /** `mutateGroup` sets this; plain `mutate` permits a non-invertible single call. */
  readonly requireUndo: boolean;
}

/** Complete server result state for one query scope inside a confirmed batch. */
export interface MaterializerQueryUpdate {
  readonly query: AnyQueryDecl;
  readonly params: Record<string, unknown>;
  readonly puts?: readonly Row[];
  readonly deletes?: readonly string[];
  readonly order: readonly string[];
  readonly status: MaterializerQueryStatus;
}

/** One atomic confirmed input to the materializer. */
export interface MaterializerServerBatch {
  readonly queries: readonly MaterializerQueryUpdate[];
  /** Commands whose confirmed rows are present in this same batch. */
  readonly settledCommandIds?: readonly string[];
}

/** Terminal or pending result returned by the proof command boundary. */
export interface MaterializerCommandResult {
  readonly state: 'pending' | 'confirmed' | 'rejected' | 'failed' | 'orphaned';
  readonly message?: string;
}

/** One public notification emitted after a complete view has replaced the prior view. */
export interface MaterializerPublication {
  readonly revision: number;
  readonly changedTables: ReadonlySet<string>;
}

/** Counters used to compare rebuild cost and publication count during Phase 0B. */
export interface MaterializerMetrics {
  readonly preflights: number;
  readonly rebuilds: number;
  readonly tableClones: number;
  readonly commandReplays: number;
  readonly memberReplays: number;
  readonly publications: number;
}

interface PreparedCall {
  readonly mutation: AnyMutationDecl;
  readonly args: Record<string, unknown>;
  readonly ids: readonly string[];
}

interface PendingCommand {
  readonly mutationId: string;
  readonly calls: readonly PreparedCall[];
  readonly inverses: readonly InverseSpec[];
  readonly requireUndo: boolean;
  readonly writes: readonly RecordedWrite[];
}

interface QueryScope {
  readonly key: string;
  readonly query: AnyQueryDecl;
  readonly params: Record<string, unknown>;
  readonly order: readonly string[];
  readonly status: MaterializerQueryStatus;
}

interface PublishedView {
  readonly revision: number;
  readonly tables: Tables;
  readonly queryRows: ReadonlyMap<string, readonly Row[]>;
  readonly queryStatuses: ReadonlyMap<string, MaterializerQueryStatus>;
  readonly queryTables: ReadonlyMap<string, string>;
}

interface BuildResult {
  readonly view: PublishedView;
  readonly pending: readonly PendingCommand[];
  readonly outcomes: readonly [string, MaterializerCommandResult][];
}

interface MutableMetrics {
  preflights: number;
  rebuilds: number;
  tableClones: number;
  commandReplays: number;
  memberReplays: number;
  publications: number;
}

/** Canonical identity for one declared query and parameter object. */
export function materializerQueryKey(query: AnyQueryDecl, params: Record<string, unknown>): string {
  return `${query.name}|${canonicalParams(params)}`;
}

function tableReader(tables: Tables): CacheReader {
  return {
    get: (table, id) => tableMap(tables, table.name).get(id) as never,
    list: (table) => [...tableMap(tables, table.name).values()] as never
  };
}

function rowsEqual(left: readonly Row[] | undefined, right: readonly Row[] | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.length !== right.length) return false;
  return left.every((row, index) => row === right[index]);
}

function statusEqual(left: MaterializerQueryStatus | undefined, right: MaterializerQueryStatus | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.kind !== right.kind) return false;
  if (left.kind === 'stale' && right.kind === 'stale') return left.error === right.error;
  if (left.kind === 'error' && right.kind === 'error') return left.error === right.error;
  return true;
}

function mapEqual(left: ReadonlyMap<string, Row> | undefined, right: ReadonlyMap<string, Row> | undefined): boolean {
  if (left === right) return true;
  if (!left || !right || left.size !== right.size) return false;
  for (const [key, value] of left) {
    if (right.get(key) !== value) return false;
  }
  return true;
}

/**
 * Standalone Wheel materializer used only by the Phase 0B proof.
 *
 * Every mutating method stages confirmed and optimistic work first. The class
 * swaps its readable view and calls listeners only after the stage succeeds.
 */
export class WheelMaterializer {
  readonly #listeners = new Set<(publication: MaterializerPublication) => void>();
  readonly #outcomes = new Map<string, MaterializerCommandResult>();
  readonly #metrics: MutableMetrics = {
    preflights: 0,
    rebuilds: 0,
    tableClones: 0,
    commandReplays: 0,
    memberReplays: 0,
    publications: 0
  };
  #confirmed: Tables = new Map();
  #scopes = new Map<string, QueryScope>();
  #pending: readonly PendingCommand[] = [];
  #view: PublishedView = {
    revision: 0,
    tables: new Map(),
    queryRows: new Map(),
    queryStatuses: new Map(),
    queryTables: new Map()
  };

  constructor(
    private readonly options: {
      readonly actor: string;
      readonly now: () => number;
    }
  ) {}

  /** Current publication revision. It changes once per accepted state input. */
  revision(): number {
    return this.#view.revision;
  }

  /** Subscribe to final publications. Intermediate rebuild state is never passed to listeners. */
  onPublish(listener: (publication: MaterializerPublication) => void): () => void {
    this.#listeners.add(listener);
    return () => this.#listeners.delete(listener);
  }

  /** Read one row from the current effective view. */
  get<RowT extends Row>(table: TableDecl<RowT>, id: string): RowT | undefined {
    return tableMap(this.#view.tables, table.name).get(id) as RowT | undefined;
  }

  /** Read every pooled row of one table from the current effective view. */
  rows<RowT extends Row>(table: TableDecl<RowT>): readonly RowT[] {
    return [...tableMap(this.#view.tables, table.name).values()] as RowT[];
  }

  /** Read the current effective rows for one declared query scope. */
  queryRows<Params extends Record<string, unknown>, RowT extends Row>(
    query: QueryDecl<Params, RowT>,
    params: Params
  ): readonly RowT[] {
    return (this.#view.queryRows.get(materializerQueryKey(query, params)) ?? []) as readonly RowT[];
  }

  /** Read lifecycle state for a query, including an empty result. */
  queryStatus<Params extends Record<string, unknown>, RowT extends Row>(
    query: QueryDecl<Params, RowT>,
    params: Params
  ): MaterializerQueryStatus | undefined {
    return this.#view.queryStatuses.get(materializerQueryKey(query, params));
  }

  /** Current state for a command removed during replay or explicitly settled. */
  commandState(mutationId: string): MaterializerCommandResult | undefined {
    if (this.#pending.some((command) => command.mutationId === mutationId)) return { state: 'pending' };
    return this.#outcomes.get(mutationId);
  }

  /** Reverse-ordered inverses captured for one pending command. */
  commandInverses(mutationId: string): readonly InverseSpec[] {
    return this.#pending.find((command) => command.mutationId === mutationId)?.inverses ?? [];
  }

  /** Pending command IDs in semantic replay order. */
  pendingCommandIds(): readonly string[] {
    return this.#pending.map((command) => command.mutationId);
  }

  /** Phase 0B allocation, replay, and publication counters. */
  metrics(): MaterializerMetrics {
    return { ...this.#metrics };
  }

  /**
   * Apply one atomic server batch, then replay surviving pending commands.
   * Query updates contain complete final order but may contain delta-only puts.
   */
  applyServerBatch(batch: MaterializerServerBatch): void {
    const nextConfirmed = this.#cloneTables(this.#confirmed);
    const nextScopes = new Map(this.#scopes);
    const pruneCandidates = new Map<string, Set<string>>();
    const seenScopes = new Set<string>();

    for (const update of batch.queries) {
      const parsedParams = update.query.params.safeParse(update.params);
      if (!parsedParams.success || !jsonParseIsIdentity(update.params, parsedParams.data)) {
        throw new Error(`Params for materializer query "${update.query.name}" are invalid.`);
      }
      validateJsonValue(`Params for materializer query "${update.query.name}"`, parsedParams.data);
      const params = parsedParams.data as Record<string, unknown>;
      const key = materializerQueryKey(update.query, params);
      if (seenScopes.has(key)) throw new Error(`Materializer batch contains query scope "${key}" twice.`);
      seenScopes.add(key);

      const order = [...update.order];
      const orderSet = new Set<string>();
      for (const id of order) {
        if (typeof id !== 'string' || id.trim() === '' || orderSet.has(id)) {
          throw new Error(`Materializer query "${update.query.name}" has an invalid or duplicate order key.`);
        }
        orderSet.add(id);
      }
      const deletes = new Set(update.deletes ?? []);
      for (const id of deletes) {
        if (orderSet.has(id)) {
          throw new Error(`Materializer query "${update.query.name}" both deletes and retains row "${id}".`);
        }
      }

      const table = update.query.into;
      const tableRows = tableMap(nextConfirmed, table.name);
      for (const [index, raw] of (update.puts ?? []).entries()) {
        const row = freezeRow({
          ...validateRow(`materializer query ${update.query.name}`, table.schema, raw)
        });
        const id = validateTableKey(table, row, `Materializer query "${update.query.name}" put ${index}`);
        tableRows.set(id, row);
      }

      const candidates = pruneCandidates.get(table.name) ?? new Set<string>();
      for (const id of deletes) candidates.add(id);
      const previous = nextScopes.get(key);
      for (const id of previous?.order ?? []) {
        if (!orderSet.has(id)) candidates.add(id);
      }
      pruneCandidates.set(table.name, candidates);
      nextScopes.set(key, {
        key,
        query: update.query,
        params,
        order: Object.freeze(order),
        status: update.status
      });
    }

    for (const scope of nextScopes.values()) {
      const rows = tableMap(nextConfirmed, scope.query.into.name);
      for (const id of scope.order) {
        if (!rows.has(id)) {
          throw new Error(`Materializer query "${scope.query.name}" order references missing row "${id}".`);
        }
      }
    }
    this.#pruneUnclaimed(nextConfirmed, nextScopes, pruneCandidates);

    const settled = new Set(batch.settledCommandIds ?? []);
    const nextPending = this.#pending.filter((command) => !settled.has(command.mutationId));
    for (const mutationId of settled) {
      if (!this.#pending.some((command) => command.mutationId === mutationId)) {
        throw new Error(`Cannot settle unknown materializer command "${mutationId}".`);
      }
    }
    const built = this.#build(nextConfirmed, nextScopes, nextPending);
    this.#confirmed = nextConfirmed;
    this.#scopes = nextScopes;
    this.#pending = built.pending;
    for (const mutationId of settled) this.#outcomes.set(mutationId, { state: 'confirmed' });
    for (const [mutationId, result] of built.outcomes) this.#outcomes.set(mutationId, result);
    this.#publish(built.view);
  }

  /**
   * Validate and enqueue one single or grouped command. Group inverse failure
   * returns `failed` before the readable view changes.
   */
  enqueue(command: MaterializerCommand): MaterializerCommandResult {
    if (command.calls.length === 0) return { state: 'confirmed' };
    if (command.calls.length > 128) {
      const result = { state: 'failed', message: 'A mutation group may contain at most 128 members.' } as const;
      this.#outcomes.set(command.mutationId, result);
      return result;
    }
    if (this.#pending.some((pending) => pending.mutationId === command.mutationId) || this.#outcomes.has(command.mutationId)) {
      const result = { state: 'failed', message: `Duplicate materializer command "${command.mutationId}".` } as const;
      this.#outcomes.set(command.mutationId, result);
      return result;
    }

    const prepared: PreparedCall[] = [];
    for (const call of command.calls) {
      const parsed = call.mutation.args.safeParse(call.args);
      if (!parsed.success || !jsonParseIsIdentity(call.args, parsed.data)) {
        const result = {
          state: 'failed',
          message: `Args for mutation "${call.mutation.name}" are invalid.`
        } as const;
        this.#outcomes.set(command.mutationId, result);
        return result;
      }
      try {
        validateJsonValue(`Args for mutation "${call.mutation.name}"`, parsed.data);
      } catch (error) {
        const result = { state: 'failed', message: String((error as Error)?.message ?? error) } as const;
        this.#outcomes.set(command.mutationId, result);
        return result;
      }
      prepared.push({
        mutation: call.mutation as AnyMutationDecl,
        args: parsed.data,
        ids: Object.freeze([...call.ids])
      });
    }

    this.#metrics.preflights += 1;
    const preflight = this.#cloneTables(this.#view.tables);
    const inverses: InverseSpec[] = [];
    try {
      for (const call of prepared) {
        const inverse = call.mutation.invert?.(tableReader(preflight), call.args) ?? null;
        if (command.requireUndo && inverse === null) {
          const result = {
            state: 'failed',
            message: `Mutation "${call.mutation.name}" is not invertible in this state.`
          } as const;
          this.#outcomes.set(command.mutationId, result);
          return result;
        }
        if (inverse) inverses.unshift(inverse);
        this.#applyCall(preflight, call, false);
      }
    } catch (error) {
      const result = error instanceof OrphanedError
        ? ({ state: 'orphaned', message: error.message } as const)
        : ({ state: 'failed', message: String((error as Error)?.message ?? error) } as const);
      this.#outcomes.set(command.mutationId, result);
      return result;
    }

    const pending: PendingCommand = {
      mutationId: command.mutationId,
      calls: Object.freeze(prepared),
      inverses: Object.freeze(inverses),
      requireUndo: command.requireUndo,
      writes: Object.freeze([])
    };
    const built = this.#build(this.#confirmed, this.#scopes, [...this.#pending, pending]);
    this.#pending = built.pending;
    for (const [mutationId, result] of built.outcomes) this.#outcomes.set(mutationId, result);
    this.#publish(built.view);
    return this.commandState(command.mutationId) ?? { state: 'failed', message: 'Command disappeared during replay.' };
  }

  /** Remove a rejected, failed, or orphaned command and publish the surviving replay. */
  removeCommand(mutationId: string, state: 'rejected' | 'failed' | 'orphaned'): boolean {
    if (!this.#pending.some((command) => command.mutationId === mutationId)) return false;
    const built = this.#build(
      this.#confirmed,
      this.#scopes,
      this.#pending.filter((command) => command.mutationId !== mutationId)
    );
    this.#pending = built.pending;
    this.#outcomes.set(mutationId, { state });
    for (const [failedId, result] of built.outcomes) this.#outcomes.set(failedId, result);
    this.#publish(built.view);
    return true;
  }

  /** Release one query scope and prune confirmed rows with no remaining server claim. */
  releaseQuery(query: AnyQueryDecl, params: Record<string, unknown>): boolean {
    const key = materializerQueryKey(query, params);
    const released = this.#scopes.get(key);
    if (!released) return false;
    const nextConfirmed = this.#cloneTables(this.#confirmed);
    const nextScopes = new Map(this.#scopes);
    nextScopes.delete(key);
    this.#pruneUnclaimed(
      nextConfirmed,
      nextScopes,
      new Map([[released.query.into.name, new Set(released.order)]])
    );
    const built = this.#build(nextConfirmed, nextScopes, this.#pending);
    this.#confirmed = nextConfirmed;
    this.#scopes = nextScopes;
    this.#pending = built.pending;
    for (const [mutationId, result] of built.outcomes) this.#outcomes.set(mutationId, result);
    this.#publish(built.view);
    return true;
  }

  #cloneTables(tables: Tables): Tables {
    this.#metrics.tableClones += 1;
    return cloneTables(tables);
  }

  #applyCall(tables: Tables, call: PreparedCall, replay: boolean): readonly RecordedWrite[] {
    if (replay) this.#metrics.memberReplays += 1;
    const overlay = new OverlayCache(tables);
    let nextId = 0;
    call.mutation.optimistic?.(overlay, call.args, {
      actor: this.options.actor,
      now: this.options.now,
      newId: (prefix: string) => {
        const id = call.ids[nextId];
        nextId += 1;
        if (id === undefined) {
          throw new Error(`Mutation "${call.mutation.name}" exhausted its deterministic ID stream.`);
        }
        if (!id.startsWith(`${prefix}_`)) {
          throw new Error(`Mutation "${call.mutation.name}" expected a "${prefix}_" deterministic ID.`);
        }
        return id;
      }
    });
    if (nextId !== call.ids.length) {
      throw new Error(`Mutation "${call.mutation.name}" left deterministic IDs unused.`);
    }
    return overlay.writes;
  }

  #build(
    confirmed: Tables,
    scopes: ReadonlyMap<string, QueryScope>,
    pending: readonly PendingCommand[]
  ): BuildResult {
    this.#metrics.rebuilds += 1;
    let working = this.#cloneTables(confirmed);
    const surviving: PendingCommand[] = [];
    const outcomes: Array<[string, MaterializerCommandResult]> = [];
    const touched = new Map<string, Set<string>>();

    for (const command of pending) {
      this.#metrics.commandReplays += 1;
      const commandFork = this.#cloneTables(working);
      const writes: RecordedWrite[] = [];
      try {
        for (const call of command.calls) writes.push(...this.#applyCall(commandFork, call, true));
      } catch (error) {
        outcomes.push([
          command.mutationId,
          error instanceof OrphanedError
            ? { state: 'orphaned', message: error.message }
            : { state: 'failed', message: String((error as Error)?.message ?? error) }
        ]);
        continue;
      }
      working = commandFork;
      for (const write of writes) {
        const ids = touched.get(write.table) ?? new Set<string>();
        ids.add(write.rowId);
        touched.set(write.table, ids);
      }
      surviving.push({ ...command, writes: Object.freeze(writes) });
    }

    const queryRows = new Map<string, readonly Row[]>();
    const queryStatuses = new Map<string, MaterializerQueryStatus>();
    const queryTables = new Map<string, string>();
    for (const scope of scopes.values()) {
      const rows = tableMap(working, scope.query.into.name);
      const ids = scope.order.filter((id) => rows.has(id));
      if (scope.query.projection) {
        const membership = new Set(ids);
        for (const id of touched.get(scope.query.into.name) ?? []) {
          const row = rows.get(id);
          if (row && scope.query.projection.filter(row, scope.params)) membership.add(id);
          else membership.delete(id);
        }
        ids.splice(0, ids.length, ...membership);
      }
      const result = ids.map((id) => rows.get(id)).filter((row): row is Row => row !== undefined);
      if (scope.query.projection?.sort) result.sort(scope.query.projection.sort);
      queryRows.set(scope.key, Object.freeze(result));
      queryStatuses.set(scope.key, scope.status);
      queryTables.set(scope.key, scope.query.into.name);
    }

    return {
      view: {
        revision: this.#view.revision + 1,
        tables: working,
        queryRows,
        queryStatuses,
        queryTables
      },
      pending: Object.freeze(surviving),
      outcomes
    };
  }

  #pruneUnclaimed(
    tables: Tables,
    scopes: ReadonlyMap<string, QueryScope>,
    candidates: ReadonlyMap<string, ReadonlySet<string>>
  ): void {
    for (const [tableName, ids] of candidates) {
      const claimed = new Set<string>();
      for (const scope of scopes.values()) {
        if (scope.query.into.name === tableName) {
          for (const id of scope.order) claimed.add(id);
        }
      }
      const rows = tableMap(tables, tableName);
      for (const id of ids) {
        if (!claimed.has(id)) rows.delete(id);
      }
    }
  }

  #changedTables(next: PublishedView): Set<string> {
    const changed = new Set<string>();
    const tableNames = new Set([...this.#view.tables.keys(), ...next.tables.keys()]);
    for (const tableName of tableNames) {
      if (!mapEqual(this.#view.tables.get(tableName), next.tables.get(tableName))) changed.add(tableName);
    }
    const queryKeys = new Set([...this.#view.queryRows.keys(), ...next.queryRows.keys()]);
    for (const key of queryKeys) {
      if (
        !rowsEqual(this.#view.queryRows.get(key), next.queryRows.get(key)) ||
        !statusEqual(this.#view.queryStatuses.get(key), next.queryStatuses.get(key))
      ) {
        const tableName = next.queryTables.get(key) ?? this.#view.queryTables.get(key);
        if (tableName) changed.add(tableName);
      }
    }
    return changed;
  }

  #publish(next: PublishedView): void {
    const changedTables = this.#changedTables(next);
    this.#view = next;
    this.#metrics.publications += 1;
    const publication: MaterializerPublication = {
      revision: next.revision,
      changedTables
    };
    for (const listener of this.#listeners) listener(publication);
  }
}
