import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { createSchemaSpec } from '../packages/wheel/src/sync/server/schema-spec';

interface SchemaInput {
  readonly syncModules: object[];
  readonly servers: object[];
}

function isSchemaInput(value: unknown): value is SchemaInput {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const input = value as Partial<SchemaInput>;
  return Array.isArray(input.syncModules) && Array.isArray(input.servers);
}

function fingerprint(input: SchemaInput): string {
  return createSchemaSpec(input).rowSchemaFingerprint;
}

function literal(value: string): string {
  return `'${value}'`;
}

function generatedModule(input: unknown): string {
  if (isSchemaInput(input)) {
    return [
      '/** Generated by `bun run row-schema`; do not edit. */',
      `export const ROW_SCHEMA_FINGERPRINT = ${literal(fingerprint(input))} as const;`,
      ''
    ].join('\n');
  }
  if (typeof input !== 'object' || input === null || Array.isArray(input)) {
    throw new TypeError('The fingerprint input must be a schema input or a named input record.');
  }
  const entries = Object.entries(input as Record<string, unknown>)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => {
      if (!isSchemaInput(value)) throw new TypeError(`Fingerprint input ${JSON.stringify(name)} is invalid.`);
      return [name, fingerprint(value)] as const;
    });
  return [
    '/** Generated by `bun run row-schema`; do not edit. */',
    'export const ROW_SCHEMA_FINGERPRINTS = {',
    ...entries.map(([name, value]) => `  ${name}: ${literal(value)},`),
    '} as const;',
    ''
  ].join('\n');
}

const [modulePath, exportName, outputPath, mode] = process.argv.slice(2);
if (!modulePath || !exportName || !outputPath || (mode !== undefined && mode !== '--check')) {
  throw new Error(
    'Usage: bun scripts/generate-row-fingerprints.ts <module> <export> <output> [--check]'
  );
}

const moduleUrl = pathToFileURL(resolve(modulePath)).href;
const source = (await import(moduleUrl)) as Record<string, unknown>;
const input = source[exportName];
const generated = generatedModule(input);
const destination = resolve(outputPath);

if (mode === '--check') {
  let existing = '';
  try {
    existing = readFileSync(destination, 'utf8');
  } catch {
    // The comparison below reports the output path that needs generation.
  }
  if (existing !== generated) {
    throw new Error(`${outputPath} is stale. Run bun run row-schema and commit the result.`);
  }
} else {
  writeFileSync(destination, generated);
}
