/**
 * Markdown rendering (settled Q4: `marked`, tracker-only dep). Raw HTML in
 * the source is DROPPED via renderer overrides — everything reaching
 * innerHTML was generated by marked from text, so user input can't smuggle
 * markup through.
 */
import { Marked } from 'marked';
import type { JSX } from 'solid-js';
import { viewRoot } from 'wheel/core';

const renderer = new Marked({
  breaks: true,
  renderer: {
    html: () => ''
  }
});

/** Render a markdown string (block layout, raw HTML stripped). */
export function Markdown(props: { source: string; class?: string }): JSX.Element {
  return (
    <div
      use:viewRoot={{ name: 'Markdown', props }}
      class={props.class}
      innerHTML={renderer.parse(props.source, { async: false })}
    />
  );
}
